### ISSUE TITLE
rails pg database.yml 配置

### ISSUE THREAD

**Issue by defrur** [defrur/daily-issue#1]
举例如下。其中 host 是不能少的。
```
development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rails_assets_development
  pool: 30
  username: homestead
  password: "secret"
```
